version: '2'
services:
    rabbit:
        hostname: rabbit
        #image: rabbitmq:latest
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "4369:4369"
            - "5671:5671"
            - "5672:5672"
            - "15672:15672"
            - "8080:8080"
        volumes:
            - /mnt/volume_fra1_01/data/rabbitmq:/var/lib/rabbitmq/
       
    worker:
        environment:
            - C_FORCE_ROOT=true 
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - .:/app
        links:
            - rabbit
            - database
        depends_on:
            - rabbit
            - database
    database:
        hostname: database
        container_name: "database"
        image: mongo:latest
        volumes:
            - /mnt/volume_fra1_01/data/mongodb:/data/db
        ports:
            - "27017:27017"
