version: '2'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5673:5672"

    worker:
        environment:
            - C_FORCE_ROOT=true 
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - .:/app
        links:
            - rabbit
            - database
        depends_on:
            - rabbit
            - database
        #command: ["celery", "-A", "test_celery", "worker","--concurrency","20","--loglevel","info"]
    database:
        hostname: database
        container_name: "database"
        image: mongo:latest
        ports:
            - "27017:27017"
